export const MEGA_EVOLUTIONS = [
  { base: 'venusaur', mega: 'venusaur-mega', stone: 'Venusaurite', types: ['grass', 'poison'] },
  { base: 'charizard', mega: 'charizard-mega-x', stone: 'Charizardite X', types: ['fire', 'dragon'] },
  { base: 'charizard', mega: 'charizard-mega-y', stone: 'Charizardite Y', types: ['fire', 'flying'] },
  { base: 'blastoise', mega: 'blastoise-mega', stone: 'Blastoisinite', types: ['water'] },
  { base: 'alakazam', mega: 'alakazam-mega', stone: 'Alakazite', types: ['psychic'] },
  { base: 'gengar', mega: 'gengar-mega', stone: 'Gengarite', types: ['ghost', 'poison'] },
  { base: 'kangaskhan', mega: 'kangaskhan-mega', stone: 'Kangaskhanite', types: ['normal'] },
  { base: 'pinsir', mega: 'pinsir-mega', stone: 'Pinsirite', types: ['bug', 'flying'] },
  { base: 'gyarados', mega: 'gyarados-mega', stone: 'Gyaradosite', types: ['water', 'dark'] },
  { base: 'aerodactyl', mega: 'aerodactyl-mega', stone: 'Aerodactylite', types: ['rock', 'flying'] },
  { base: 'mewtwo', mega: 'mewtwo-mega-x', stone: 'Mewtwonite X', types: ['psychic', 'fighting'] },
  { base: 'mewtwo', mega: 'mewtwo-mega-y', stone: 'Mewtwonite Y', types: ['psychic'] },
  { base: 'ampharos', mega: 'ampharos-mega', stone: 'Ampharosite', types: ['electric', 'dragon'] },
  { base: 'scizor', mega: 'scizor-mega', stone: 'Scizorite', types: ['bug', 'steel'] },
  { base: 'heracross', mega: 'heracross-mega', stone: 'Heracronite', types: ['bug', 'fighting'] },
  { base: 'houndoom', mega: 'houndoom-mega', stone: 'Houndoominite', types: ['dark', 'fire'] },
  { base: 'tyranitar', mega: 'tyranitar-mega', stone: 'Tyranitarite', types: ['rock', 'dark'] },
  { base: 'blaziken', mega: 'blaziken-mega', stone: 'Blazikenite', types: ['fire', 'fighting'] },
  { base: 'gardevoir', mega: 'gardevoir-mega', stone: 'Gardevoirite', types: ['psychic', 'fairy'] },
  { base: 'mawile', mega: 'mawile-mega', stone: 'Mawilite', types: ['steel', 'fairy'] },
  { base: 'aggron', mega: 'aggron-mega', stone: 'Aggronite', types: ['steel'] },
  { base: 'medicham', mega: 'medicham-mega', stone: 'Medichamite', types: ['fighting', 'psychic'] },
  { base: 'manectric', mega: 'manectric-mega', stone: 'Manectite', types: ['electric'] },
  { base: 'banette', mega: 'banette-mega', stone: 'Banettite', types: ['ghost'] },
  { base: 'absol', mega: 'absol-mega', stone: 'Absolite', types: ['dark'] },
  { base: 'garchomp', mega: 'garchomp-mega', stone: 'Garchompite', types: ['dragon', 'ground'] },
  { base: 'lucario', mega: 'lucario-mega', stone: 'Lucarionite', types: ['fighting', 'steel'] },
  { base: 'abomasnow', mega: 'abomasnow-mega', stone: 'Abomasite', types: ['grass', 'ice'] },
  { base: 'gallade', mega: 'gallade-mega', stone: 'Galladite', types: ['psychic', 'fighting'] },
  { base: 'audino', mega: 'audino-mega', stone: 'Audinite', types: ['normal', 'fairy'] },
  { base: 'diancie', mega: 'diancie-mega', stone: 'Diancite', types: ['rock', 'fairy'] },
  { base: 'latias', mega: 'latias-mega', stone: 'Latiasite', types: ['dragon', 'psychic'] },
  { base: 'latios', mega: 'latios-mega', stone: 'Latiosite', types: ['dragon', 'psychic'] },
  { base: 'swampert', mega: 'swampert-mega', stone: 'Swampertite', types: ['water', 'ground'] },
  { base: 'sceptile', mega: 'sceptile-mega', stone: 'Sceptilite', types: ['grass', 'dragon'] },
  { base: 'sableye', mega: 'sableye-mega', stone: 'Sablenite', types: ['dark', 'ghost'] },
  { base: 'altaria', mega: 'altaria-mega', stone: 'Altarianite', types: ['dragon', 'fairy'] },
  { base: 'glalie', mega: 'glalie-mega', stone: 'Glalitite', types: ['ice'] },
  { base: 'salamence', mega: 'salamence-mega', stone: 'Salamencite', types: ['dragon', 'flying'] },
  { base: 'metagross', mega: 'metagross-mega', stone: 'Metagrossite', types: ['steel', 'psychic'] },
  { base: 'rayquaza', mega: 'rayquaza-mega', stone: 'Rayquaza must know Dragon Ascent', types: ['dragon', 'flying'] },
  { base: 'lopunny', mega: 'lopunny-mega', stone: 'Lopunnite', types: ['normal', 'fighting'] },
  { base: 'groudon', mega: 'groudon-primal', stone: 'Red Orb', types: ['ground', 'fire'] },
  { base: 'kyogre', mega: 'kyogre-primal', stone: 'Blue Orb', types: ['water'] },
  { base: 'beedrill', mega: 'beedrill-mega', stone: 'Beedrillite', types: ['bug', 'poison'] },
  { base: 'pidgeot', mega: 'pidgeot-mega', stone: 'Pidgeotite', types: ['normal', 'flying'] },
  { base: 'slowbro', mega: 'slowbro-mega', stone: 'Slowbronite', types: ['water', 'psychic'] },
  { base: 'steelix', mega: 'steelix-mega', stone: 'Steelixite', types: ['steel', 'ground'] },
  { base: 'sharpedo', mega: 'sharpedo-mega', stone: 'Sharpedonite', types: ['water', 'dark'] },
  { base: 'camerupt', mega: 'camerupt-mega', stone: 'Cameruptite', types: ['fire', 'ground'] },
  { base: 'altaria', mega: 'altaria-mega', stone: 'Altarianite', types: ['dragon', 'fairy'] },
]

export const GIGANTAMAX = [
  { base: 'venusaur', gmax: 'venusaur-gmax', move: 'G-Max Vine Lash' },
  { base: 'charizard', gmax: 'charizard-gmax', move: 'G-Max Wildfire' },
  { base: 'blastoise', gmax: 'blastoise-gmax', move: 'G-Max Cannonade' },
  { base: 'butterfree', gmax: 'butterfree-gmax', move: 'G-Max Befuddle' },
  { base: 'pikachu', gmax: 'pikachu-gmax', move: 'G-Max Volt Crash' },
  { base: 'meowth', gmax: 'meowth-gmax', move: 'G-Max Gold Rush' },
  { base: 'machamp', gmax: 'machamp-gmax', move: 'G-Max Chi Strike' },
  { base: 'gengar', gmax: 'gengar-gmax', move: 'G-Max Terror' },
  { base: 'kingler', gmax: 'kingler-gmax', move: 'G-Max Foam Burst' },
  { base: 'lapras', gmax: 'lapras-gmax', move: 'G-Max Resonance' },
  { base: 'eevee', gmax: 'eevee-gmax', move: 'G-Max Cuddle' },
  { base: 'snorlax', gmax: 'snorlax-gmax', move: 'G-Max Replenish' },
  { base: 'garbodor', gmax: 'garbodor-gmax', move: 'G-Max Malodor' },
  { base: 'melmetal', gmax: 'melmetal-gmax', move: 'G-Max Meltdown' },
  { base: 'corviknight', gmax: 'corviknight-gmax', move: 'G-Max Wind Rage' },
  { base: 'orbeetle', gmax: 'orbeetle-gmax', move: 'G-Max Gravitas' },
  { base: 'drednaw', gmax: 'drednaw-gmax', move: 'G-Max Stonesurge' },
  { base: 'coalossal', gmax: 'coalossal-gmax', move: 'G-Max Volcalith' },
  { base: 'flapple', gmax: 'flapple-gmax', move: 'G-Max Tartness' },
  { base: 'appletun', gmax: 'appletun-gmax', move: 'G-Max Sweetness' },
  { base: 'sandaconda', gmax: 'sandaconda-gmax', move: 'G-Max Sandblast' },
  { base: 'toxtricity', gmax: 'toxtricity-amped-gmax', move: 'G-Max Stun Shock' },
  { base: 'centiskorch', gmax: 'centiskorch-gmax', move: 'G-Max Centiferno' },
  { base: 'hatterene', gmax: 'hatterene-gmax', move: 'G-Max Smite' },
  { base: 'grimmsnarl', gmax: 'grimmsnarl-gmax', move: 'G-Max Snooze' },
  { base: 'alcremie', gmax: 'alcremie-gmax', move: 'G-Max Finale' },
  { base: 'copperajah', gmax: 'copperajah-gmax', move: 'G-Max Steelsurge' },
  { base: 'duraludon', gmax: 'duraludon-gmax', move: 'G-Max Depletion' },
  { base: 'urshifu', gmax: 'urshifu-single-strike-gmax', move: 'G-Max One Blow' },
]

export const FORM_FAMILIES = [
  { name: 'Rotom', base: 'rotom', forms: ['rotom', 'rotom-heat', 'rotom-wash', 'rotom-frost', 'rotom-fan', 'rotom-mow'] },
  { name: 'Deoxys', base: 'deoxys', forms: ['deoxys-normal', 'deoxys-attack', 'deoxys-defense', 'deoxys-speed'] },
  { name: 'Shaymin', base: 'shaymin', forms: ['shaymin-land', 'shaymin-sky'] },
  { name: 'Giratina', base: 'giratina', forms: ['giratina-altered', 'giratina-origin'] },
  { name: 'Kyurem', base: 'kyurem', forms: ['kyurem', 'kyurem-black', 'kyurem-white'] },
  { name: 'Necrozma', base: 'necrozma', forms: ['necrozma', 'necrozma-dusk-mane', 'necrozma-dawn-wings', 'necrozma-ultra'] },
  { name: 'Zygarde', base: 'zygarde', forms: ['zygarde-10', 'zygarde-50', 'zygarde-complete'] },
  { name: 'Oricorio', base: 'oricorio', forms: ['oricorio-baile', 'oricorio-pom-pom', 'oricorio-pau', 'oricorio-sensu'] },
  { name: 'Lycanroc', base: 'lycanroc', forms: ['lycanroc-midday', 'lycanroc-midnight', 'lycanroc-dusk'] },
  { name: 'Tatsugiri', base: 'tatsugiri', forms: ['tatsugiri-curly', 'tatsugiri-droopy', 'tatsugiri-stretchy'] },
  { name: 'Palafin', base: 'palafin', forms: ['palafin-zero', 'palafin-hero'] },
]

export const REGIONAL_SUFFIXES = ['-alola', '-galar', '-hisui', '-paldea']
